//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/UI/Input Actions/SwipeTrack.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SwipeTrack : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SwipeTrack()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SwipeTrack"",
    ""maps"": [
        {
            ""name"": ""SwipeMovement"",
            ""id"": ""08ced236-a343-4a6b-b155-da1344a85ee0"",
            ""actions"": [
                {
                    ""name"": ""SwipeTrack"",
                    ""type"": ""Value"",
                    ""id"": ""7012efc1-23d8-4da8-a937-ba3470ebaa74"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e8a5e0ed-28bf-43ad-b1e7-e38b1cfb9042"",
                    ""path"": ""<Touchscreen>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwipeTrack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SwipeMovement
        m_SwipeMovement = asset.FindActionMap("SwipeMovement", throwIfNotFound: true);
        m_SwipeMovement_SwipeTrack = m_SwipeMovement.FindAction("SwipeTrack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SwipeMovement
    private readonly InputActionMap m_SwipeMovement;
    private ISwipeMovementActions m_SwipeMovementActionsCallbackInterface;
    private readonly InputAction m_SwipeMovement_SwipeTrack;
    public struct SwipeMovementActions
    {
        private @SwipeTrack m_Wrapper;
        public SwipeMovementActions(@SwipeTrack wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwipeTrack => m_Wrapper.m_SwipeMovement_SwipeTrack;
        public InputActionMap Get() { return m_Wrapper.m_SwipeMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SwipeMovementActions set) { return set.Get(); }
        public void SetCallbacks(ISwipeMovementActions instance)
        {
            if (m_Wrapper.m_SwipeMovementActionsCallbackInterface != null)
            {
                @SwipeTrack.started -= m_Wrapper.m_SwipeMovementActionsCallbackInterface.OnSwipeTrack;
                @SwipeTrack.performed -= m_Wrapper.m_SwipeMovementActionsCallbackInterface.OnSwipeTrack;
                @SwipeTrack.canceled -= m_Wrapper.m_SwipeMovementActionsCallbackInterface.OnSwipeTrack;
            }
            m_Wrapper.m_SwipeMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SwipeTrack.started += instance.OnSwipeTrack;
                @SwipeTrack.performed += instance.OnSwipeTrack;
                @SwipeTrack.canceled += instance.OnSwipeTrack;
            }
        }
    }
    public SwipeMovementActions @SwipeMovement => new SwipeMovementActions(this);
    public interface ISwipeMovementActions
    {
        void OnSwipeTrack(InputAction.CallbackContext context);
    }
}
